In [1]:
import numpy as np

In [1]:
import numpy as np

# Create a simple 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

# Create a simple 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(array_2d)

# Accessing elements of the array
print("\nAccessing elements:")
print("Element at index 0 of array_1d:", array_1d[0])
print("Element at row 1, column 2 of array_2d:", array_2d[1, 2])

# Performing basic operations
array_1d_sum = np.sum(array_1d)
print("\nSum of elements in array_1d:", array_1d_sum)

array_2d_mean = np.mean(array_2d)
print("Mean of elements in array_2d:", array_2d_mean)

# Reshaping an array
reshaped_array = np.reshape(array_1d, (5, 1))
print("\nReshaped array:")
print(reshaped_array)


1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Accessing elements:
Element at index 0 of array_1d: 1
Element at row 1, column 2 of array_2d: 6

Sum of elements in array_1d: 15
Mean of elements in array_2d: 5.0

Reshaped array:
[[1]
 [2]
 [3]
 [4]
 [5]]


In [2]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}

df = pd.DataFrame(data)

# Displaying the DataFrame
print("DataFrame:")
print(df)

# Accessing specific columns
print("\nAccessing 'Name' column:")
print(df['Name'])

# Accessing specific rows
print("\nAccessing row 1:")
print(df.iloc[1])

# Basic statistics
print("\nMean age:", df['Age'].mean())
print("Maximum age:", df['Age'].max())


DataFrame:
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

Accessing 'Name' column:
0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

Accessing row 1:
Name            Bob
Age              30
City    Los Angeles
Name: 1, dtype: object

Mean age: 32.5
Maximum age: 40
